# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup
title: Trovalet Denis - Portfolio Chimie Verte

# Hero Section
name: Trovalet Denis
headline: Étudiant en Master Chimie Verte - Synthèse Durable & Catalyse
description: >-
  Étudiant en Master Chimie Verte à l'Université de Strasbourg (2025-2026). Passionné par les approches durables en synthèse organique, catalyse (homo/hétérogène) et valorisation de la biomasse. Expérience en TP de synthèse et détermination structurale. À la recherche d'un stage en R&D pour appliquer mes compétences en chimie verte à des projets industriels innovants. Maîtrise de l'anglais et du français pour des collaborations internationales.

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/avatar.jpeg  # Ajoute ta photo ici

# Link your resume
resume-url: /assets/resume/cv-chimie-verte.pdf  # Upload ton CV PDF ou lien externe

# Set up external links - Ajoute tes vrais liens
external-links:
  linkedin:  # Ex. : "trovalet-denis"
  github:    # Ex. : "trovaletdenis"

# Skills Section - Adapté à ton Master
skills:
  - category: Chimie Fondamentale
    tools:
    - Chimie Organique (synthèse et stratégies vertes)
    - Chimie Inorganique et de Coordination
    - Chimie Organométallique
    - Chimie Supramoléculaire
  - category: Catalyse & Synthèse Durable
    tools:
    - Catalyse Homogène et Hétérogène
    - Biocatalyse et Organocatalyse
    - Valorisation de la Biomasse
    - Approches Vertes en Synthèse Organique
  - category: Analyse & Évaluation Environnementale
    tools:
    - Analyse de Cycle de Vie (ACV)
    - Évaluation des Impacts Environnementaux
    - Droit de l'Environnement
    - Spectroscopies pour Détermination Structurale
  - category: Outils Expérimentaux
    tools:
    - TP de Synthèse et Chimie Physique
    - Projet Interdisciplinaire en Durabilité (PID)
    - Normes et Réglementations Chimiques

# Contact Form Setup
formspree-key:  # Colle ta clé Formspree ici

# Active theme - Thème mint pour un look éco
colors:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"

# Build settings (ne change pas)
collections:
  projects:
    output: true
    permalink: /projects/:path/

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
